accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

bbs/urls.py
from django.urls import path
from . import views
from .models import Article
from django.views import generic

app_name = 'bbs'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('create/', views.CreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
]

contact/urls.py
from django.urls import path
from . import views


app_name = 'contact'

urlpatterns = [
        path('', views.index, name='index'),  # 一覧画面
        path('contact_form/', views.contact_form, name='contact_form'),  # フォーム
        path('contact_form/contact/complete/', views.complete, name='complete'),  # 完了画面
]

myapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/bbs/')),
    path('index.html', RedirectView.as_view(url='/bbs/')),
    path('bbs/', include('bbs.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('contact.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

bbs/models.py
from django.db import models
from django.urls import reverse

class Article(models.Model):
    title = models.CharField(max_length = 200)
    content = models.TextField(max_length=1000)

    author = models.ForeignKey(
        'auth.User',
        on_delete = models.CASCADE,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

    def get_absolute_url(self):
        return reverse('bbs:detail', kwargs={'pk': self.pk})

contact/models.py
from django.db import models

# Create your models here.

contact/forms.py
from django import forms


class ContactForm(forms.Form):
    subject = forms.CharField(label='件名', max_length=100)
    sender = forms.EmailField(label='Email', help_text='※ご確認の上、正しく入力してください。')
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)
    myself = forms.BooleanField(label='同じ内容を受け取る', required=False)

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

bbs/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Article
from django.views import generic

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied

def index(request):
    return HttpResponse('Hello Django')

def detail(request, id):
    return HttpResponse('detail ' + str(id))

def create(request):
    return HttpResponse('create')

class UpdateView(LoginRequiredMixin, generic.edit.UpdateView):
    model = Article
    fields = ['content', 'title', ]
 
    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
 
        if obj.author != self.request.user:
            raise PermissionDenied('You do not have permission to edit.')
 
        return super(UpdateView, self).dispatch(request, *args, **kwargs)

class DeleteView(LoginRequiredMixin, generic.edit.DeleteView):
    model = Article
    success_url = reverse_lazy('bbs:index')

class IndexView(generic.ListView):
    model = Article

class DetailView(generic.DetailView):
    model = Article

class CreateView(LoginRequiredMixin, generic.edit.CreateView):
    model = Article
    fields = ['content', 'title', ]

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(CreateView, self).form_valid(form)

contact/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from .forms import ContactForm
from django.http import HttpResponse
from django.conf import settings
from django.core.mail import BadHeaderError, send_mail

""" 一覧画面"""
def index(request):
    return render(request, 'contact/index.html')


""" お問い合わせフォーム画面"""
def contact_form(request):
    return render(request, 'contact/contact_form.html')


""" 送信完了画面"""
def complete(request):
    return render(request, 'contact/complete.html')

def contact_form(request):

    if request.method == 'POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            return redirect('contact:complete')

    else:
        form = ContactForm()

    return render(request, 'contact/contact_form.html', {'form': form})

def contact_form(request):

    if request.method == 'POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            """ 追記"""
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']
            myself = form.cleaned_data['myself']
            recipients = [settings.EMAIL_HOST_USER]

            if myself:
                recipients.append(sender)
            try:
                send_mail(subject, message, sender, recipients)
            except BadHeaderError:
                return HttpResponse('無効なヘッダーが見つかりました。')
            return redirect('contact:complete')

    else:
        form = ContactForm()

    return render(request, 'contact/contact_form.html', {'form': form})

accounts/templates/accounts/signup.html
{% extends 'layout.html' %}

{% block content %}
<h1>ユーザー登録</h1>
<section class='common-form'>
    <form method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type='submit'>登録</button>
    </form>
</section>
{% endblock %}

bbs/templates/bbs/article_confirm_delete.html
{% extends 'layout.html' %}

{% block content %}

<h1>投稿の削除</h1>
<p>以下を削除しますか?</p>
<p>{{ article.content }}</p>
<p>{{ article.user_name }}</p>
<p>{{ article.author }}</p>
<p>{{ article.created_at|date:"Y-m-j H:i:s" }}</p>
<p>{{ article.updated_at|date:"Y-m-j H:i:s" }}</p>

<form action='' method='post'>{% csrf_token %}
    <a href='JavaScript:history.back()' class='btn btn-outline-primary'>削除しないで戻る</a>
    <button type='submit' class='submit delete btn btn-danger'>削除する</button>
</form>

{% endblock %}

bbs/templates/bbs/article_detail.html
{% extends 'layout.html' %}

{% block content %}

<div>
    <p>タイトル：{{ article.title }}</p>
    <p>投稿内容：<br>{{ article.content }}</p>
    <p>{{ article.author }}</p>
    <p>{{ article.created_at|date:"Y-m-j H:i:s" }}<br>
    {{ article.updated_at|date:"Y-m-j H:i:s" }}</p>
</div>
<div class='mt-4'>
    {% if request.user.id == object.author_id %}
    <a href='{% url "bbs:update" article.pk %}'  class='btn btn-outline-primary mr-2'>編集</a>
    {% endif %}

    <a href='{% url "bbs:index" %}' class='btn btn-outline-primary'>一覧に戻る</a>

    {% if request.user.id == object.author_id %}
    <a href='{% url "bbs:delete" article.pk %}'  class='btn btn-danger ml-5'>削除</a>
    {% endif %}
</div>
{% endblock %}

bbs/templates/bbs/article_form.html
{% extends 'layout.html' %}

{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h1 class="mt-5 mb-4">{{ object|yesno:'投稿内容の更新,新規投稿の作成'}}</h1>

            <form action='' method='post'>
                {% csrf_token %}
                <div class="form-group">
                    <label for="title" class="font-weight-bold">タイトル：</label>
                    {{ form.title }}
                </div>
                <div class="form-group">
                    <label for="content" class="font-weight-bold">本文：</label>
                    {{ form.content }}
                </div>
                <button type='submit' class='btn btn-primary btn-block'>{{ object|yesno:'更新,作成'}}</button>
            </form>
            <div class="mt-3">
                <a href='JavaScript:history.back()' class='btn btn-outline-secondary btn-block'>< 戻る</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

bbs/templates/bbs/article_list.html
{% extends 'layout.html' %}

{% block content %}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="mt-5 mb-4 text-center">投稿一覧</h1>

                <div class="list-group">
                    {% for article in object_list %}
                    <a href='{% url "bbs:detail" article.pk %}' class="list-group-item list-group-item-action">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">{{ article.title }}</h5>
                            <small>{{ article.created_at|date:"Y-m-j H:i" }}</small>
                        </div>
                        <p class="mb-1">{{ article.content }}</p>
                        <small>投稿者: {{ article.author }}</small>
                    </a>
                    {% endfor %}
                </div>

                {% if user.is_authenticated %}
                <div class="text-center mt-4">
                    <a href='{% url "bbs:create" %}' class='btn btn-primary'>新規投稿</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

bbs/templates/bbs/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
        <style>body {padding-top: 80px;}</style>
        <title>鳩でもわかるはじめてのDjango</title>
    </head>
    <body>
        <nav class='navbar navbar-expand-sm navbar-dark bg-dark fixed-top'>
            <a class='navbar-brand' href='{% url "bbs:index" %}'>BBS TOP</a>
        </nav>
        <div class='container'>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

contact/templates/contact/complete.html
{% extends 'layout.html' %}
{% block content %}
<center>
    <h1>送信完了</h1>
    <a href="{% url 'contact:index' %}">
        <p>トップへ</p>
    </a>
</center>
{% endblock %}

contact/templates/contact/contact_form.html
{% extends 'layout.html' %}
{% block content %}
<center>
    <h1>入力フォーム</h1><hr>
    <br>
    <form action="{% url 'contact:contact_form' %}" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
    <br>
        <input type="submit" value="送信">
    </form>
</center>
{% endblock %}

contact/templates/contact/index.html
{% extends 'layout.html' %}
{% block content %}
<!DOCTYPE html>
<html>
    <head>

        <title>Webサイト</title>

    </head>
    <body>

        <center>
            <a href="{% url 'contact:contact_form' %}">
                <h2>お問い合わせフォーム</h2>
            </a>
        </center>

    </body>
</html>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
        <style>
            body {padding-top: 80px;}
            h1 {font-size: 150%;}
            h2 {font-size: 130%;}
            h3 {font-size: 110%;}
            h4 {font-size: 100%;}
            h5 {font-size: 100%;}
            h6 {font-size: 100%;}
        </style>
        <title>Twitter</title>
    </head>
    <body>
        <nav class='navbar navbar-expand-sm navbar-dark bg-dark fixed-top'>
            <a class='navbar-brand' href='{% url "bbs:index" %}'>Twitter</a>
            <ul class='navbar-nav'>
                {% if user.is_authenticated %}
                    <!-- ログインしているとき -->
                    <li class='nav-time'>
                        <span class='navbar-text'>{{ user }} - </span>
                    </li>
                    <li class='nav-item'>
                        <a href='{% url "logout" %}' class='logout nav-link'>ログアウト</a>
                    </li>
                    <li class='nav-item'>
                        <a href='{% url "contact:contact_form" %}' class='form nav-link'>お問い合わせ</a>
                    </li>
                {% else %}
                    <!-- ログインしていないとき -->
                    <li class="nav-item">
                        <a href='{% url "login" %}' class='login nav-link'>ログイン</a>
                    </li>
                    <li class="nav-item">
                        <a href='{% url "accounts:signup" %}' class='signup nav-link'>ユーザー登録</a>
                    </li>
                    <li class='nav-item'>
                        <a href='{% url "contact:contact_form" %}' class='form nav-link'>お問い合わせ</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
        <div class='container'>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>